services:
  client:
    build:
      context: ./client
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: client
    ports:
      - "${CLIENT_PORT}:80"
    env_file:
      - .env

  server:
    build:
      context: ./server
      args:
        SERVER_PORT: ${SERVER_PORT}
    container_name: server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - query_llm_service
      - mock_api

  query_llm_service:
    build:
      context: ./query_llm_service
    container_name: query_llm_service
    env_file:
      - .env
    networks:
      - app-network
    expose:
      - "8000"

  mock_api:
    build:
      context: ./mock_api
    container_name: mock_api_service
    env_file:
      - .env
    networks:
      - app-network
    expose:
      - "8000"

networks:
  app-network:
    driver: bridge
